### ISSUE TITLE
C# example code for Get an Accept Payment Page should return a class of getHostedPaymentPageResponse rather than ANetApiResponse

### ISSUE THREAD

**Issue by johnswu** [AuthorizeNet/sample-code-csharp#100]
The example code is misleading because the ANetApiResponse class does not have the attribute 'token', which is what gets populated by the call to GetApiResponse.  It should actually return the derived class, getHostedPaymentPageResponse.

**Comment by gnongsie** [comment]
Hi,
The GetApiResponse method inside the controller will return the proper derived class in each case. This is why the token object is being printed properly.

You can check the Travis logs for confirmation on the same.

**Comment by johnswu** [comment]
The GetApiResponse method does correctly return the proper derived class, but the example Run function in GetAnAcceptPaymentPage.cs returns the ANetApiResponse class.  When I tried to use this code to get a token, I got compile errors because 'token' was not part of the ANetApiResponse class.

**Comment by gnongsie** [comment]
Hi,
I'm sorry but I still don't think that is an issue.

I've tested this and I am able to access the token. I just need to type cast the response.
````
var response = GetAnAcceptPaymentPage.Run(apiLoginId, transactionKey, 12.23m);
Console.WriteLine( ( (getHostedPaymentPageResponse) response).token );
````

**Comment by johnswu** [comment]
Ok - it was just a suggestion.
