### ISSUE TITLE
gGetHostedProfilePageResponse request not implemented

### ISSUE THREAD

**Issue by dhanuka777** [AuthorizeNet/sample-code-csharp#20]
It is nessasary to have gGetHostedProfilePageResponse to make tokenized credit card payments. As per the http://www.authorize.net/content/dam/authorize/documents/CIM_XML_guide.pdf document, chapter 4. But there is no implementation in the sample code. Solution from the community member can be found in http://community.developer.authorize.net/t5/Integration-and-Testing/How-to-call-GetHostedProfilePage/td-p/14208. I used it and it works. Please implement this missing method.

**Comment by brianmc** [comment]
Hi @dhanuka777 we just added that sample:

<img width="791" alt="screen shot 2015-10-10 at 8 49 54 am" src="https://cloud.githubusercontent.com/assets/1022976/10411967/ff49400e-6f2b-11e5-905f-0797fb182fa1.png">
