### ISSUE TITLE
ChargeCreditCard.cs or sample code doesn't generate declines?  How do you verify address or zip?

### ISSUE THREAD

**Issue by cltw** [AuthorizeNet/sample-code-csharp#30]
ChargeCreditCard.cs or sample code doesn't generate declines?  How do you verify address or zip?

**Comment by gauravmokhasi** [comment]
Address verification is done at the processors and not by Authorize.net. Authorize.net therefore has a simulator that lets you generate specific AVS responses for testing purposes. See http://developer.authorize.net/hello_world/testing_guide/ for more details. You would specify zip=46282 to get a general declined transaction.

**Comment by rhldr** [comment]
I believe @cltw is asking us to add Address and Zipcode fields to the sample code to understand how these values are passed in the request

**Comment by cltw** [comment]
Right the ChargeCreditCard.cs does not pass in those values, so how then could they be magically verified? Do I need to use the  AuthorizeCreditCard.cs  and CapturePreviouslyAuthorizedAmount.cs instead?

**Comment by gauravmokhasi** [comment]
zip is an optional parameter, which is probably why it isn't included in ChargeCreditCard.cs. Here's how you can add it.

``` C#
var paymentType = new paymentType { Item = creditCard };
customerAddressType billingZip = new customerAddressType { zip = 46282 };
// 46282 generates a decline; give another value for zip if you want the transaction to go through

var transactionRequest = new transactionRequestType
{
  transactionType = transactionTypeEnum.authCaptureTransaction.ToString(), // charge the card
  amount = 133.45m,
  payment = paymentType,
  billTo = billingZip
};
```

For more information on optional fields, see http://developer.authorize.net/api/reference/index.html#payment-transactions-charge-a-credit-card

**Comment by cltw** [comment]
Thank you so much!  I will try it out.  Same thing for address then?  customerAddressType billingAddress = new customerAddressType { address = "123 Sesame St." };

**Comment by gauravmokhasi** [comment]
You're welcome :) Yes, same thing. But remember, there's only one `billTo` in `transactionRequest`. So if you want to submit both address and zip in the same request, your object would change to something like `customerAddressType addressDetails = new customerAddressType { address = "123 Sesame St", zip = 45000 };` and `billTo = addressDetails`

**Comment by cltw** [comment]
Ok thanks!

**Comment by cltw** [comment]
Just real quick, to test this verification of zip/address, does the sandbox have capability to test the decline codes or do I need to do this in test mode on the merchant's?

**Comment by cltw** [comment]
Sorry to drag this out. If I add the email parameter, will authorize.net send a confirmation email out to the client?  If not, do u have an idea how to do that?  customerAddressType addressDetails = new customerAddressType { address = "123 Sesame St", zip = "45000", email="asfd@asdf.com" };?
           
and then testing it all, does the sandbox have capability to test the decline codes, mismatch address/zip or do I need to do this in test mode on the merchant's?  I've tried testing for error codes and have gotten successful responses...  thanks again.

**Comment by cltw** [comment]
Does email paramater  go in the customerAddressType, or customerDataType?  Intellisense shows both.  I need to send email so authorize.net can auto-send a confirmation email.

customerAddressType addressDetails = new customerAddressType { address = a_address, city = a_city, state = a_state, country = a_country, zip = a_zip };

```
        var transactionRequest = new transactionRequestType
        {
            transactionType = transactionTypeEnum.authCaptureTransaction.ToString(),   
            amount = a_amount,//133.45m,
            payment = paymentType,
            billTo = addressDetails,
            customer = new customerDataType { email = "_@live.com"}

        };
```

**Comment by brianmc** [comment]
email goes in customerDataType but it looks like you've already figured that one out.  Thanks for the feedback.
