### ISSUE TITLE
sample code doesn't generate email from authorize.net to send to customer?

### ISSUE THREAD

**Issue by cltw** [AuthorizeNet/sample-code-csharp#31]
Need authorize.net to send an email through code.  How is that done?

**Comment by brianmc** [comment]
Hi citw, we'll add that sample code shortly.  It's very similar to https://github.com/AuthorizeNet/sample-code-csharp/blob/master/TransactionReporting/GetTransactionDetails.cs except use the sendCustomerTransactionReceiptRequest object and add customerEmail as an additional parameter.

**Comment by cltw** [comment]
thanks I'll see what I can figure out.  I tried going off the documentation
and the intellisense provides email parameters in two different spots.
Will either of these work?



customerAddressType addressDetails = new customerAddressType { address =
a_address, city = a_city, state = a_state, country = a_country, zip =
a_zip, email = "_@live.com" };



var transactionRequest = new transactionRequestType
{
transactionType = transactionTypeEnum.authCaptureTransaction.ToString(),
amount = a_amount,//133.45m,
payment = paymentType,
billTo = addressDetails,

};



OR

customerAddressType addressDetails = new customerAddressType { address =
a_address, city = a_city, state = a_state, country = a_country, zip = a_zip
};

customerDataType email = new customerDataType { email = "_@live.com" };



var transactionRequest = new transactionRequestType
{
transactionType = transactionTypeEnum.authCaptureTransaction.ToString(),
amount = a_amount,//133.45m,
payment = paymentType,
billTo = addressDetails,
customer = email

};

 thx

On Thu, Oct 29, 2015 at 9:24 AM, Brian McManus <notifications@github.com>
wrote:

> Hi citw, we'll add that sample code shortly. It's very similar to
> https://github.com/AuthorizeNet/sample-code-csharp/blob/master/TransactionReporting/GetTransactionDetails.cs
> except use the sendCustomerTransactionReceiptRequest object and add
> customerEmail as an additional parameter.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AuthorizeNet/sample-code-csharp/issues/31#issuecomment-152195932>
> .
>



-- 
Tammy Walters

**Comment by cltw** [comment]
I tried to put together some code and did not succeed, I got a null response.  Could you point out where I went wrong?  Also, will the sandbox be able to send a confirmation email?  Thanks.

```
 var request = new createTransactionRequest { transactionRequest = transactionRequest };
        // instantiate the contoller that will call the service
        var controller = new createTransactionController(request);
        controller.Execute();
        //get the response from the service (errors contained if any)
        var response = controller.GetApiResponse();

        var sendrequest = new sendCustomerTransactionReceiptRequest();
        sendrequest.transId = response.transactionResponse.TransID;
        sendrequest.customerEmail = email;

        var sendController = new sendCustomerTransactionReceiptController(sendrequest);
        sendController.Execute();

        var sendResponse = sendController.GetApiResponse();
```

**Comment by brianmc** [comment]
Hi @cltw, apologies for the delay in responding back.  Here's the XML and yes the sandbox will sen the emails.

```
<sendCustomerTransactionReceiptRequest  xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd">
      <merchantAuthentication>
        <name>Your_apilogin_id</name>
        <transactionKey>Your_transaction_key</transactionKey>
      </merchantAuthentication>
      <transId>txn_id</transId>
      <customerEmail>user@mail.com</customerEmail>
</sendCustomerTransactionReceiptRequest >
```
