### ISSUE TITLE
How to include lineItems in this model

### ISSUE THREAD

**Issue by mortonr** [AuthorizeNet/sample-code-csharp#38]
I am trying to include lineItems using this model.  Any suggestions would be great.  Code snip below:

 //standard api call to retrieve response
            var paymentType = new paymentType { Item = creditCard };

```
        var orderDetails = new orderType { invoiceNumber = "Inv 01234", description = "Test" };

        var items = new lineItemType { itemId = "TESTER", description = "Dec", name="Name", quantity = 1, taxable = false, taxableSpecified = false, unitPrice = 0.10m };


        var transactionRequest = new transactionRequestType
        {
            transactionType = transactionTypeEnum.authCaptureTransaction.ToString(),    // charge the card
            //amount = 133.45m,
            amount = Amount,
            payment = paymentType,
            order = orderDetails,
            lineItems = items

        };
```

**Comment by rjsnyderdesign** [comment]
Thank you for asking this question. I thought I was the only one struggling with this.

**Comment by brianmc** [comment]
We updated the ChargeCreditCard sample with example of adding line items: https://github.com/AuthorizeNet/sample-code-csharp/commit/e8859d15d10c1608f63add31aee5b38806249595 

Hope this helps, any issues let us know.
