### ISSUE TITLE
Confusion around validating successful transactions

### ISSUE THREAD

**Issue by rmorrin** [AuthorizeNet/sample-code-csharp#40]
Hi there,

While integrating Authorize.Net into a client project, we came across some unexpected issues when testing against a live account, using real payment information.

From your own sample code for `ChargeCreditCard.Run`:

``` csharp
// get the response from the service (errors contained if any)
var response = controller.GetApiResponse();

if (response.messages.resultCode == messageTypeEnum.Ok)
{
    if (response.transactionResponse != null)
    {
        Console.WriteLine("Success, Auth Code : " + response.transactionResponse.authCode);
    }
}
else
{
    Console.WriteLine("Error: " + response.messages.message[0].code + "  " + response.messages.message[0].text);
    if (response.transactionResponse != null)
    {
        Console.WriteLine("Transaction Error : " + response.transactionResponse.errors[0].errorCode + " " + response.transactionResponse.errors[0].errorText);
    }
}

...
```

This seems to suggest that `response.messages.resultCode` can be used to determine success of the overall transaction. During our testing however, this was found not to be the case. When using a live account, and intentionally entering incorrect information we regularly saw a resultCode of `Ok`, despite the transaction itself being declined and errors being returned.

I was only able to find limited documentation surrounding the sample code, which all seemed to suggest that `messages.resultCode` could be relied upon to confirm a successful transaction. However, It's definitely possible that I've missed something!

---

As a temporary workaround, we've resorted to _also_ checking `response.transactionResponse.responseCode` as well as the errors collection returned by the transaction response:

``` csharp
if (response.messages.resultCode == messageTypeEnum.Ok && response.transactionResponse != null &&
    response.transactionResponse.responseCode == "1" &&
    (response.transactionResponse.errors == null || !response.transactionResponse.errors.Any()))
{
    // successful transaction
}
```

This works as we would like, but feels wrong. For the majority of cases, it's only important for us to check that the transaction was successful, and requiring this number of checks to confirm does seem a little excessive!

Just for others' benefit, it's also worth mentioning that this was only discovered when moving over to a 'live' account; using sandbox/test accounts did not surface the issue, as transactions were always returned as successful during testing.

**Comment by brianmc** [comment]
Hi Ryan,

I think we need to update our sample code in the PaymentTransactions section to make this clearer.  We have tried to be more explicit in our new ResponseCodes tool http://developer.authorize.net/api/reference/responseCodes.html but that hasn't been made explicit enough in our sample code or some other documentation.  

For payment transaction API calls (e.g. charging cards as opposed to API calls like createSubscription) there is a second level of error code which represents the credit card processors result for that transaction and that is the level which you must inspect at.   This also explains why you are only seeing some of these responses with real data, in our sandbox we can only simulate processor scenarios but we cannot process real cards.  We do provide trigger values which will help out with testing processor response scenarios:  http://developer.authorize.net/hello_world/testing_guide/  

Thanks for the feedback, apologies for the confusion, we'll make sure to get the sample code and docs updated to avoid this situation going forward.  Any follow on question feel free to give us a shout.

Brian
