### ISSUE TITLE
Email is not posted - Charge Credit Card

### ISSUE THREAD

**Issue by schernokov** [AuthorizeNet/sample-code-csharp#46]
Email is not posted when using customerAddressType. The credit card is charged successfully. However, when I login to authorize.net account and pull up the transaction, the billing email is blank - apparently it is not posted.

Here is an example  from my code: 
var billingAddress = new customerAddressType
            {
                firstName = _tran.first_name,
                lastName = _tran.last_name,

```
            address = _tran.address,
            city = _tran.city,
            state = _tran.state,
            zip = _tran.zip,
            country = _tran.country,
            email = _tran.email_address,
            phoneNumber = _tran.phone_num,   //phone number won't be posted to Authorize.net
        };
```

**Comment by sunnyrajrathod** [comment]
Yes, currently the email does not seem to be posted in the request, as part of customerAddressType.
To send the customer email address, add it as part of customerDataType.
Example:
```

 var customerInfo = new customerDataType
            {
                id = "1234",
                email = "asd@asd.com";
            };
```
followed by
```
var transactionRequest = new transactionRequestType
            {
                transactionType = transactionTypeEnum.authCaptureTransaction.ToString(),    // charge the card

                amount = amount,
                payment = paymentType,
                billTo = billingAddress,
                lineItems = lineItems,
                customer = customerInfo
            };
```

**Comment by schernokov** [comment]
Thank you very much for answering! I really appreciate it.
Could you please answer one more question? I tried to set the setting not to email the customer (automated email) because, my app will email a better receipt. I instantiated an array of settingType and set settingValue="FALSE" (see below). I included the array into transactionRequestType object. However, the transaction fails; the response message is "This transaction cannot be processed.".
Please let me know your thoughts on what I am doing wrong.

           var arTransactionSettings = new settingType[1];
            var setting = new settingType
            {
                settingName = settingNameEnum.emailCustomer.ToString(),
                settingValue = "FALSE"
            };
            arTransactionSettings[0] = setting;


            var transactionRequest = new transactionRequestType
            {
                transactionType = transactionTypeEnum.authCaptureTransaction.ToString(),  
                amount = amount,
                payment = paymentType,
                customer = customerInfo,
                billTo = billingAddress,
                order = thisOrder,
                solution = solutionSoftware,
                transactionSettings = arTransactionSettings
            };

**Comment by schernokov** [comment]
Thank you for the answer. It worked!
