### ISSUE TITLE
.Net Core Suppot

### ISSUE THREAD

**Issue by schwietertj** [AuthorizeNet/sample-code-csharp#49]
Are there plans to support .Net Core?

**Comment by brianmc** [comment]
Hi @schwietertj, yes we certainly hope to support .Net Core and we're currently looking into it.  We already run our Travis CI builds on Mono (linux) so we're hopefully that's a good indicator that we won't have too much work to do.

Thanks for the suggestion,

Brian

**Comment by schwietertj** [comment]
@brianmc thank you very much for the update
