### ISSUE TITLE
The underlying connection was closed

### ISSUE THREAD

**Issue by ffchris** [AuthorizeNet/sample-code-csharp#58]
I ran the latest C# version of the sample code "ChargeCreditCard", but cannot seem to get past the  error, "The underlying connection was closed: "

 var controller = new createTransactionController(request);
            controller.Execute();

I verified my sandbox ApiLoginID and ApiTransactionKey work on the Authorize.net website: https://developer.authorize.net/api/reference/

It seems others are having this issue, but we haven't found a solution:
https://community.developer.authorize.net/t5/Integration-and-Testing/Sandbox-issues-The-underlying-connection-was-closed-An/td-p/57584

**Comment by ashtru** [comment]
- What is the further stacktrace of the error?
- Have you tried the TLS 1.2 fix as stated in the discussion [here](https://community.developer.authorize.net/t5/Integration-and-Testing/Sandbox-issues-The-underlying-connection-was-closed-An/m-p/57887#M32569) ? See the highlighted message by *gheitman* . 

If your client (sample code) uses .Net Framework 4.6.1 , ideally TLS 1.2 should be used by default.

**Comment by ffchris** [comment]
I was able to fix this by updating the code to use Tls12 right before creating the transaction:

 System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;
            var request = new createTransactionRequest { transactionRequest = transactionRequest };
