### ISSUE TITLE
Cannot set grant permission for paypal account

### ISSUE THREAD

**Issue by taquocy** [AuthorizeNet/sample-code-csharp#60]
I have created account PayPal sandbox mode(Not add bank account information). Then I set grant permission from account Authorize.Net  and the error message always appear "There has been an error while processing your request. Please try again."
So How I resolve this issue ?

**Comment by adavidw** [comment]
Hi @taquocy,

My apologies, but I'm closing this issue as it's not directly related to the c# sample code or the .NET SDK.
