### ISSUE TITLE
Using

### ISSUE THREAD

**Issue by asimDev** [AuthorizeNet/sample-code-csharp#66]
#  Could not load file or assembly 'AuthorizeNet        

var controller = new createCustomerProfileController(request);
            controller.Execute();
            // get the response from the service (errors contained if any)
            createCustomerProfileResponse response = controller.GetApiResponse();
            
**When trying to use above getting the error below:**
S_### erver Error in '/' Application.

Could not load file or assembly 'AuthorizeNet, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.IO.FileLoadException: Could not load file or assembly 'AuthorizeNet, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)_

**Comment by asimDev** [comment]
Okay, The Answer is make sure your Anti-Virus is turned Off.

Best help is self -help

**Comment by Purushottamlpa** [comment]
Do you still have any concern, if no we can close this ticket?

**Comment by Purushottamlpa** [comment]
Thanks for the concern. Since, we didn't hear any update from you, we are closing this issue. If you need further assistance please raise a new issue.
