### ISSUE TITLE
The type System.String may not be used in this context. The clientId is not coming back in the request.

### ISSUE THREAD

**Issue by hetaldave** [AuthorizeNet/sample-code-csharp#69]
I have implemented this test method and getting the error below. Any help would be great.
The same code works fine in my other application though.

 public static object Ping()
        {
            ApiOperationBase<ANetApiRequest, ANetApiResponse>.MerchantAuthentication = new merchantAuthenticationType()
            {
                name = "5KP3u95bQpv",
                ItemElementName = ItemChoiceType.transactionKey,
                Item = "346HZ32z3fP4hTG2"
            };

            ApiOperationBase<ANetApiRequest, ANetApiResponse>.RunEnvironment = AuthorizeNet.Environment.SANDBOX;

            authenticateTestRequest request = new authenticateTestRequest();
           
           var controller = new authenticateTestController(request);
           controller.Execute();

            var response = controller.GetApiResponse();

            return response;
        }
![2018-06-11_17-42-29](https://user-images.githubusercontent.com/8376501/41258698-22b97382-6d9f-11e8-956d-37659b443060.png)

**Comment by Purushottamlpa** [comment]
Hi hetaldave,

We tried to replicate your issue, but its working fine. 

   // define the merchant information (authentication / transaction id)
            ApiOperationBase<ANetApiRequest, ANetApiResponse>.MerchantAuthentication = new merchantAuthenticationType()
            {
                name = "5KP3u95bQpv",
                ItemElementName = ItemChoiceType.transactionKey,
                Item = "346HZ32z3fP4hTG2",
            };

            authenticateTestRequest testRequest = new authenticateTestRequest();

            var testController = new authenticateTestController(testRequest);
            testController.Execute();
            var testresponse = testController.GetApiResponse();

Could you please share which version of SDK you are using?

**Comment by chsriniv9** [comment]
Closing this issue based on the post by @Purushottamlpa. Please feel free to re-open if you have any further query.
