### ISSUE TITLE
Build Errors and Warnings

### ISSUE THREAD

**Issue by JonathanJamesRasmussen** [AuthorizeNet/sample-code-csharp#83]
I'm unable to build the SampleCode project after following the instructions in the README.md.  I've attached a log of errors and warnings I get when I try and build the project.
[sample-code-error-list.xlsx](https://github.com/AuthorizeNet/sample-code-csharp/files/2508115/sample-code-error-list.xlsx)

**Comment by ashtru** [comment]
@JonathanJamesRasmussen I am facing the same error.
Let me debug, and we will get back to you on this.

**Comment by ashtru** [comment]
Thank you, @JonathanJamesRasmussen !
We updated the project which fixed the build. 

You should be able to verify. 
Please reopen the issue in case of any problems.
