### ISSUE TITLE
Build error with SampleCode_DotNet_Core solution

### ISSUE THREAD

**Issue by kevinding0218** [AuthorizeNet/sample-code-csharp#93]
Hello, I am trying to build the "DotNet_Core" solution but getting a lot of errors, such as:
* The type or namespace name 'Utilities' does not exist in the namespace 'AuthorizeNet' (are you missing an assembly reference?) 
`-->SampleCode.cs-->using AuthorizeNet.Utilities;`
* 'Environment' does not contain a definition for 'HttpUseProxy' and no accessible extension method 'HttpUseProxy' accepting a first argument of type 'Environment' could be found (are you missing a using directive or an assembly reference?) 
`-->SampleCode.cs --> ApiOperationBase<ANetApiRequest, ANetApiResponse>.RunEnvironment.HttpUseProxy`
* The name 'Constants' does not exist in the current context
`-->SampleCode.cs --> AuthorizeNet.Environment.getBooleanProperty(Constants.HttpsUseProxy)`	
Mostly errors are occurred in **SampleCode.cs region #if NETCOREAPP2_0 part in SampleCode_DotNet_Core project**, I was wondering if it's because I installed the wrong package of AuthorizeNet, but I tried AuthorizeNet, two additional package through Nuget like AuthorizeNet.Fork.Aspcore2 and AuthorizeNetLite but all three doesn't work...

Do you have a better solution for the "DotNet_Core" project or any documentation tutorial?

Thank you very much!
Best,

**Comment by gnongsie** [comment]
Hi,

I apologize for the inconvenience you faced.

For the DotNet Core project to work, you need to use the AuthorizeNet SDK provided in [this location](https://github.com/AuthorizeNet/dotnet-core-sdk-beta/tree/master/ReleaseArtifact), instead of the one provided from Nuget.

Please switch to this DLL and let us know if you continue to face any issues.

**Comment by gnongsie** [comment]
I'll be closing this issue for now. Please contact us again if you face further issues on this point.
